/*
* generated by Xtext
*/
package org.xtext.osy.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.osy.services.ExtendedSMVGrammarAccess;

public class ExtendedSMVParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExtendedSMVGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.osy.parser.antlr.internal.InternalExtendedSMVParser createParser(XtextTokenStream stream) {
		return new org.xtext.osy.parser.antlr.internal.InternalExtendedSMVParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ExtendedSMVGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExtendedSMVGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
