/*
* generated by Xtext
*/
package org.xtext.osy;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExtendedSMVUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.osy.ui.internal.ExtendedSMVActivator.getInstance().getInjector("org.xtext.osy.ExtendedSMV");
	}
	
}
