/*
* generated by Xtext
*/
package org.xtext.osy.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ExtendedSMVGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cSectionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSectionsSectionParserRuleCall_0 = (RuleCall)cSectionsAssignment.eContents().get(0);
		
		//Model:
		//	sections+=Section*;
		public ParserRule getRule() { return rule; }

		//sections+=Section*
		public Assignment getSectionsAssignment() { return cSectionsAssignment; }

		//Section
		public RuleCall getSectionsSectionParserRuleCall_0() { return cSectionsSectionParserRuleCall_0; }
	}

	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Section");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVariablesSectionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAssignmentsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Section:
		//	VariablesSection | //| Comments
		//	Assignments;
		public ParserRule getRule() { return rule; }

		//VariablesSection | //| Comments
		//Assignments
		public Alternatives getAlternatives() { return cAlternatives; }

		//VariablesSection
		public RuleCall getVariablesSectionParserRuleCall_0() { return cVariablesSectionParserRuleCall_0; }

		////| Comments
		//Assignments
		public RuleCall getAssignmentsParserRuleCall_1() { return cAssignmentsParserRuleCall_1; }
	}

	public class CommentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Comment");
		private final Assignment cCommentAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cCommentSMV_COMMENTTerminalRuleCall_0 = (RuleCall)cCommentAssignment.eContents().get(0);
		
		//Comment:
		//	comment=SMV_COMMENT;
		public ParserRule getRule() { return rule; }

		//comment=SMV_COMMENT
		public Assignment getCommentAssignment() { return cCommentAssignment; }

		//SMV_COMMENT
		public RuleCall getCommentSMV_COMMENTTerminalRuleCall_0() { return cCommentSMV_COMMENTTerminalRuleCall_0; }
	}

	public class VariablesSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariablesSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVARKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVariablesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVariablesVariableDeclarationParserRuleCall_1_0 = (RuleCall)cVariablesAssignment_1.eContents().get(0);
		
		//VariablesSection:
		//	"VAR" variables+=VariableDeclaration+;
		public ParserRule getRule() { return rule; }

		//"VAR" variables+=VariableDeclaration+
		public Group getGroup() { return cGroup; }

		//"VAR"
		public Keyword getVARKeyword_0() { return cVARKeyword_0; }

		//variables+=VariableDeclaration+
		public Assignment getVariablesAssignment_1() { return cVariablesAssignment_1; }

		//VariableDeclaration
		public RuleCall getVariablesVariableDeclarationParserRuleCall_1_0() { return cVariablesVariableDeclarationParserRuleCall_1_0; }
	}

	public class AssignmentsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assignments");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAssignmentsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cASSIGNKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAssignmentsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAssignmentsAssignmentExpressionParserRuleCall_2_0 = (RuleCall)cAssignmentsAssignment_2.eContents().get(0);
		
		//Assignments:
		//	{Assignments} "ASSIGN" assignments+=AssignmentExpression+;
		public ParserRule getRule() { return rule; }

		//{Assignments} "ASSIGN" assignments+=AssignmentExpression+
		public Group getGroup() { return cGroup; }

		//{Assignments}
		public Action getAssignmentsAction_0() { return cAssignmentsAction_0; }

		//"ASSIGN"
		public Keyword getASSIGNKeyword_1() { return cASSIGNKeyword_1; }

		//assignments+=AssignmentExpression+
		public Assignment getAssignmentsAssignment_2() { return cAssignmentsAssignment_2; }

		//AssignmentExpression
		public RuleCall getAssignmentsAssignmentExpressionParserRuleCall_2_0() { return cAssignmentsAssignmentExpressionParserRuleCall_2_0; }
	}

	public class VariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableDeclaration");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntegerDeclarionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBooleanDeclarionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStateVariableDeclarationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCommentParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//VariableDeclaration:
		//	IntegerDeclarion | BooleanDeclarion | StateVariableDeclaration | Comment;
		public ParserRule getRule() { return rule; }

		//IntegerDeclarion | BooleanDeclarion | StateVariableDeclaration | Comment
		public Alternatives getAlternatives() { return cAlternatives; }

		//IntegerDeclarion
		public RuleCall getIntegerDeclarionParserRuleCall_0() { return cIntegerDeclarionParserRuleCall_0; }

		//BooleanDeclarion
		public RuleCall getBooleanDeclarionParserRuleCall_1() { return cBooleanDeclarionParserRuleCall_1; }

		//StateVariableDeclaration
		public RuleCall getStateVariableDeclarationParserRuleCall_2() { return cStateVariableDeclarationParserRuleCall_2; }

		//Comment
		public RuleCall getCommentParserRuleCall_3() { return cCommentParserRuleCall_3; }
	}

	public class IntegerDeclarionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntegerDeclarion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cIntegerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//IntegerDeclarion:
		//	name=ID ":" "integer" ";";
		public ParserRule getRule() { return rule; }

		//name=ID ":" "integer" ";"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//"integer"
		public Keyword getIntegerKeyword_2() { return cIntegerKeyword_2; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class BooleanDeclarionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanDeclarion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBooleanKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//BooleanDeclarion:
		//	name=ID ":" "boolean" ";";
		public ParserRule getRule() { return rule; }

		//name=ID ":" "boolean" ";"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//"boolean"
		public Keyword getBooleanKeyword_2() { return cBooleanKeyword_2; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class StateVariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StateVariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cStatesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cStatesIDTerminalRuleCall_3_0 = (RuleCall)cStatesAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStatesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStatesIDTerminalRuleCall_4_1_0 = (RuleCall)cStatesAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StateVariableDeclaration:
		//	name=ID ":" "{" states+=ID ("," states+=ID)* "}" ";";
		public ParserRule getRule() { return rule; }

		//name=ID ":" "{" states+=ID ("," states+=ID)* "}" ";"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//states+=ID
		public Assignment getStatesAssignment_3() { return cStatesAssignment_3; }

		//ID
		public RuleCall getStatesIDTerminalRuleCall_3_0() { return cStatesIDTerminalRuleCall_3_0; }

		//("," states+=ID)*
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//states+=ID
		public Assignment getStatesAssignment_4_1() { return cStatesAssignment_4_1; }

		//ID
		public RuleCall getStatesIDTerminalRuleCall_4_1_0() { return cStatesIDTerminalRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}

	public class AssignmentExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AssignmentExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntegerAssignmentParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBooleanAssignmentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStateAssignmentParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCommentParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		////VarType:
		// //	'boolean' | 'integer'
		// //;
		//AssignmentExpression:
		//	IntegerAssignment | BooleanAssignment | StateAssignment | Comment;
		public ParserRule getRule() { return rule; }

		//IntegerAssignment | BooleanAssignment | StateAssignment | Comment
		public Alternatives getAlternatives() { return cAlternatives; }

		//IntegerAssignment
		public RuleCall getIntegerAssignmentParserRuleCall_0() { return cIntegerAssignmentParserRuleCall_0; }

		//BooleanAssignment
		public RuleCall getBooleanAssignmentParserRuleCall_1() { return cBooleanAssignmentParserRuleCall_1; }

		//StateAssignment
		public RuleCall getStateAssignmentParserRuleCall_2() { return cStateAssignmentParserRuleCall_2; }

		//Comment
		public RuleCall getCommentParserRuleCall_3() { return cCommentParserRuleCall_3; }
	}

	public class BooleanAssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanAssignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cVarBooleanDeclarionCrossReference_2_0 = (CrossReference)cVarAssignment_2.eContents().get(0);
		private final RuleCall cVarBooleanDeclarionIDTerminalRuleCall_2_0_1 = (RuleCall)cVarBooleanDeclarionCrossReference_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueBOOLParserRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//BooleanAssignment:
		//	"init" "(" var=[BooleanDeclarion] ")" ":=" value=BOOL ";";
		public ParserRule getRule() { return rule; }

		//"init" "(" var=[BooleanDeclarion] ")" ":=" value=BOOL ";"
		public Group getGroup() { return cGroup; }

		//"init"
		public Keyword getInitKeyword_0() { return cInitKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//var=[BooleanDeclarion]
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }

		//[BooleanDeclarion]
		public CrossReference getVarBooleanDeclarionCrossReference_2_0() { return cVarBooleanDeclarionCrossReference_2_0; }

		//ID
		public RuleCall getVarBooleanDeclarionIDTerminalRuleCall_2_0_1() { return cVarBooleanDeclarionIDTerminalRuleCall_2_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//":="
		public Keyword getColonEqualsSignKeyword_4() { return cColonEqualsSignKeyword_4; }

		//value=BOOL
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }

		//BOOL
		public RuleCall getValueBOOLParserRuleCall_5_0() { return cValueBOOLParserRuleCall_5_0; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}

	public class BOOLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BOOL");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//BOOL:
		//	"True" | "False";
		public ParserRule getRule() { return rule; }

		//"True" | "False"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"True"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"False"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class IntegerAssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntegerAssignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cVarIntegerDeclarionCrossReference_2_0 = (CrossReference)cVarAssignment_2.eContents().get(0);
		private final RuleCall cVarIntegerDeclarionIDTerminalRuleCall_2_0_1 = (RuleCall)cVarIntegerDeclarionCrossReference_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueINTTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//IntegerAssignment:
		//	"init" "(" var=[IntegerDeclarion] ")" ":=" value=INT ";";
		public ParserRule getRule() { return rule; }

		//"init" "(" var=[IntegerDeclarion] ")" ":=" value=INT ";"
		public Group getGroup() { return cGroup; }

		//"init"
		public Keyword getInitKeyword_0() { return cInitKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//var=[IntegerDeclarion]
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }

		//[IntegerDeclarion]
		public CrossReference getVarIntegerDeclarionCrossReference_2_0() { return cVarIntegerDeclarionCrossReference_2_0; }

		//ID
		public RuleCall getVarIntegerDeclarionIDTerminalRuleCall_2_0_1() { return cVarIntegerDeclarionIDTerminalRuleCall_2_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//":="
		public Keyword getColonEqualsSignKeyword_4() { return cColonEqualsSignKeyword_4; }

		//value=INT
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_5_0() { return cValueINTTerminalRuleCall_5_0; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}

	public class StateAssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StateAssignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cVarStateVariableDeclarationCrossReference_2_0 = (CrossReference)cVarAssignment_2.eContents().get(0);
		private final RuleCall cVarStateVariableDeclarationIDTerminalRuleCall_2_0_1 = (RuleCall)cVarStateVariableDeclarationCrossReference_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueIDTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		////
		//StateAssignment:
		//	"init" "(" var=[StateVariableDeclaration] ")" ":=" value=ID ";";
		public ParserRule getRule() { return rule; }

		//"init" "(" var=[StateVariableDeclaration] ")" ":=" value=ID ";"
		public Group getGroup() { return cGroup; }

		//"init"
		public Keyword getInitKeyword_0() { return cInitKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//var=[StateVariableDeclaration]
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }

		//[StateVariableDeclaration]
		public CrossReference getVarStateVariableDeclarationCrossReference_2_0() { return cVarStateVariableDeclarationCrossReference_2_0; }

		//ID
		public RuleCall getVarStateVariableDeclarationIDTerminalRuleCall_2_0_1() { return cVarStateVariableDeclarationIDTerminalRuleCall_2_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//":="
		public Keyword getColonEqualsSignKeyword_4() { return cColonEqualsSignKeyword_4; }

		//value=ID
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_5_0() { return cValueIDTerminalRuleCall_5_0; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	
	
	private ModelElements pModel;
	private SectionElements pSection;
	private CommentElements pComment;
	private TerminalRule tSMV_COMMENT;
	private VariablesSectionElements pVariablesSection;
	private AssignmentsElements pAssignments;
	private VariableDeclarationElements pVariableDeclaration;
	private IntegerDeclarionElements pIntegerDeclarion;
	private BooleanDeclarionElements pBooleanDeclarion;
	private StateVariableDeclarationElements pStateVariableDeclaration;
	private AssignmentExpressionElements pAssignmentExpression;
	private BooleanAssignmentElements pBooleanAssignment;
	private BOOLElements pBOOL;
	private IntegerAssignmentElements pIntegerAssignment;
	private StateAssignmentElements pStateAssignment;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ExtendedSMVGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.osy.ExtendedSMV".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	sections+=Section*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Section:
	//	VariablesSection | //| Comments
	//	Assignments;
	public SectionElements getSectionAccess() {
		return (pSection != null) ? pSection : (pSection = new SectionElements());
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}

	//Comment:
	//	comment=SMV_COMMENT;
	public CommentElements getCommentAccess() {
		return (pComment != null) ? pComment : (pComment = new CommentElements());
	}
	
	public ParserRule getCommentRule() {
		return getCommentAccess().getRule();
	}

	//terminal SMV_COMMENT:
	//	"--" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSMV_COMMENTRule() {
		return (tSMV_COMMENT != null) ? tSMV_COMMENT : (tSMV_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SMV_COMMENT"));
	} 

	//VariablesSection:
	//	"VAR" variables+=VariableDeclaration+;
	public VariablesSectionElements getVariablesSectionAccess() {
		return (pVariablesSection != null) ? pVariablesSection : (pVariablesSection = new VariablesSectionElements());
	}
	
	public ParserRule getVariablesSectionRule() {
		return getVariablesSectionAccess().getRule();
	}

	//Assignments:
	//	{Assignments} "ASSIGN" assignments+=AssignmentExpression+;
	public AssignmentsElements getAssignmentsAccess() {
		return (pAssignments != null) ? pAssignments : (pAssignments = new AssignmentsElements());
	}
	
	public ParserRule getAssignmentsRule() {
		return getAssignmentsAccess().getRule();
	}

	//VariableDeclaration:
	//	IntegerDeclarion | BooleanDeclarion | StateVariableDeclaration | Comment;
	public VariableDeclarationElements getVariableDeclarationAccess() {
		return (pVariableDeclaration != null) ? pVariableDeclaration : (pVariableDeclaration = new VariableDeclarationElements());
	}
	
	public ParserRule getVariableDeclarationRule() {
		return getVariableDeclarationAccess().getRule();
	}

	//IntegerDeclarion:
	//	name=ID ":" "integer" ";";
	public IntegerDeclarionElements getIntegerDeclarionAccess() {
		return (pIntegerDeclarion != null) ? pIntegerDeclarion : (pIntegerDeclarion = new IntegerDeclarionElements());
	}
	
	public ParserRule getIntegerDeclarionRule() {
		return getIntegerDeclarionAccess().getRule();
	}

	//BooleanDeclarion:
	//	name=ID ":" "boolean" ";";
	public BooleanDeclarionElements getBooleanDeclarionAccess() {
		return (pBooleanDeclarion != null) ? pBooleanDeclarion : (pBooleanDeclarion = new BooleanDeclarionElements());
	}
	
	public ParserRule getBooleanDeclarionRule() {
		return getBooleanDeclarionAccess().getRule();
	}

	//StateVariableDeclaration:
	//	name=ID ":" "{" states+=ID ("," states+=ID)* "}" ";";
	public StateVariableDeclarationElements getStateVariableDeclarationAccess() {
		return (pStateVariableDeclaration != null) ? pStateVariableDeclaration : (pStateVariableDeclaration = new StateVariableDeclarationElements());
	}
	
	public ParserRule getStateVariableDeclarationRule() {
		return getStateVariableDeclarationAccess().getRule();
	}

	////VarType:
	// //	'boolean' | 'integer'
	// //;
	//AssignmentExpression:
	//	IntegerAssignment | BooleanAssignment | StateAssignment | Comment;
	public AssignmentExpressionElements getAssignmentExpressionAccess() {
		return (pAssignmentExpression != null) ? pAssignmentExpression : (pAssignmentExpression = new AssignmentExpressionElements());
	}
	
	public ParserRule getAssignmentExpressionRule() {
		return getAssignmentExpressionAccess().getRule();
	}

	//BooleanAssignment:
	//	"init" "(" var=[BooleanDeclarion] ")" ":=" value=BOOL ";";
	public BooleanAssignmentElements getBooleanAssignmentAccess() {
		return (pBooleanAssignment != null) ? pBooleanAssignment : (pBooleanAssignment = new BooleanAssignmentElements());
	}
	
	public ParserRule getBooleanAssignmentRule() {
		return getBooleanAssignmentAccess().getRule();
	}

	//BOOL:
	//	"True" | "False";
	public BOOLElements getBOOLAccess() {
		return (pBOOL != null) ? pBOOL : (pBOOL = new BOOLElements());
	}
	
	public ParserRule getBOOLRule() {
		return getBOOLAccess().getRule();
	}

	//IntegerAssignment:
	//	"init" "(" var=[IntegerDeclarion] ")" ":=" value=INT ";";
	public IntegerAssignmentElements getIntegerAssignmentAccess() {
		return (pIntegerAssignment != null) ? pIntegerAssignment : (pIntegerAssignment = new IntegerAssignmentElements());
	}
	
	public ParserRule getIntegerAssignmentRule() {
		return getIntegerAssignmentAccess().getRule();
	}

	////
	//StateAssignment:
	//	"init" "(" var=[StateVariableDeclaration] ")" ":=" value=ID ";";
	public StateAssignmentElements getStateAssignmentAccess() {
		return (pStateAssignment != null) ? pStateAssignment : (pStateAssignment = new StateAssignmentElements());
	}
	
	public ParserRule getStateAssignmentRule() {
		return getStateAssignmentAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
