/*
 * generated by Xtext
 */
package org.xtext.osy.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExtendedSMVUiModule extends org.xtext.osy.ui.AbstractExtendedSMVUiModule {
	public ExtendedSMVUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
