/**
 * generated by Xtext
 */
package org.xtext.osy.validation;

import org.xtext.osy.validation.AbstractExtendedSMVValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ExtendedSMVValidator extends AbstractExtendedSMVValidator {
}
