/*
 * generated by Xtext
 */
package org.xtext.osy.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.osy.ui.internal.ExtendedSMVActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExtendedSMVExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExtendedSMVActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExtendedSMVActivator.getInstance().getInjector(ExtendedSMVActivator.ORG_XTEXT_OSY_EXTENDEDSMV);
	}
	
}
