/*
 * generated by Xtext
 */
package org.xtext.osy.validation

import org.xtext.osy.extendedSMV.Module
import com.google.inject.TypeLiteral

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class ExtendedSMVValidator extends AbstractExtendedSMVValidator {

  public static val INVALID_NAME = 'invalidName'
	

	@Check
	def checkGreetingStartsWithCapital(Module modle) {
		
			warning("Name should start with a capital", 
      			null);
		
	}
	

	
}
