/*
 * generated by Xtext
 */
package org.xtext.osy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExtendedSMVRuntimeModule extends org.xtext.osy.AbstractExtendedSMVRuntimeModule {

}
