/*
* generated by Xtext
*/
package org.xtext.osy;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ExtendedSMVStandaloneSetup extends ExtendedSMVStandaloneSetupGenerated{

	public static void doSetup() {
		new ExtendedSMVStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

