/**
 * generated by Xtext
 */
package org.xtext.osy.ui.contentassist;

import org.xtext.osy.ui.contentassist.AbstractExtendedSMVProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ExtendedSMVProposalProvider extends AbstractExtendedSMVProposalProvider {
}
